/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Notak
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        cont = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        graybox = new javax.swing.JPanel();
        whitebox = new javax.swing.JPanel();
        steamtxt = new javax.swing.JLabel();
        steamicon = new javax.swing.JLabel();
        riottxt = new javax.swing.JLabel();
        rioticon = new javax.swing.JLabel();
        chrometxt = new javax.swing.JLabel();
        chromeicon = new javax.swing.JLabel();
        netbeanstxt = new javax.swing.JLabel();
        recyclingtxt = new javax.swing.JLabel();
        netbeansicon = new javax.swing.JLabel();
        recyclingbin = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        windowsbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("<html>\nWelcome to Data Defender!\n<br>\n<br>\nTo begin this game, please create an account.\n<br>\n<br> \nClick OK to begin.\n</html>");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, -1));

        cont.setText("OK");
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });
        jLayeredPane1.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 250, 80, -1));

        exit.setForeground(new java.awt.Color(153, 153, 153));
        exit.setText("X");
        jLayeredPane1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 10, -1));

        banner.setForeground(new java.awt.Color(153, 153, 153));
        banner.setText("Setup Software");
        jLayeredPane1.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        graybox.setBackground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout grayboxLayout = new javax.swing.GroupLayout(graybox);
        graybox.setLayout(grayboxLayout);
        grayboxLayout.setHorizontalGroup(
            grayboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        grayboxLayout.setVerticalGroup(
            grayboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLayeredPane1.add(graybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 300, 50));

        whitebox.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout whiteboxLayout = new javax.swing.GroupLayout(whitebox);
        whitebox.setLayout(whiteboxLayout);
        whiteboxLayout.setHorizontalGroup(
            whiteboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        whiteboxLayout.setVerticalGroup(
            whiteboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jLayeredPane1.add(whitebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, 220));

        steamtxt.setForeground(new java.awt.Color(255, 255, 255));
        steamtxt.setText("Steam");
        jLayeredPane1.add(steamtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        steamicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steamicon.png"))); // NOI18N
        jLayeredPane1.add(steamicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        riottxt.setForeground(new java.awt.Color(255, 255, 255));
        riottxt.setText("Riot Client");
        jLayeredPane1.add(riottxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        rioticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rioticon.png"))); // NOI18N
        jLayeredPane1.add(rioticon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 50));

        chrometxt.setForeground(new java.awt.Color(255, 255, 255));
        chrometxt.setText("Google Chrome");
        jLayeredPane1.add(chrometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        chromeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chromeicon.png"))); // NOI18N
        jLayeredPane1.add(chromeicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        netbeanstxt.setForeground(new java.awt.Color(255, 255, 255));
        netbeanstxt.setText("Netbeans");
        jLayeredPane1.add(netbeanstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        recyclingtxt.setForeground(new java.awt.Color(255, 255, 255));
        recyclingtxt.setText("Recycling Bin");
        jLayeredPane1.add(recyclingtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        netbeansicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/netbeansicon.png"))); // NOI18N
        jLayeredPane1.add(netbeansicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        recyclingbin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/recyclingicon.png"))); // NOI18N
        jLayeredPane1.add(recyclingbin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        title.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Data Defender");
        jLayeredPane1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 170, 60));

        windowsbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        jLayeredPane1.add(windowsbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 723, 429));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
        new PasswordChecker().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_contActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel chromeicon;
    private javax.swing.JLabel chrometxt;
    private javax.swing.JButton cont;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel graybox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel netbeansicon;
    private javax.swing.JLabel netbeanstxt;
    private javax.swing.JLabel recyclingbin;
    private javax.swing.JLabel recyclingtxt;
    private javax.swing.JLabel rioticon;
    private javax.swing.JLabel riottxt;
    private javax.swing.JLabel steamicon;
    private javax.swing.JLabel steamtxt;
    private javax.swing.JLabel title;
    private javax.swing.JPanel whitebox;
    private javax.swing.JLabel windowsbackground;
    // End of variables declaration//GEN-END:variables
}
