import java.util.Scanner;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Notak
 */
public class startemails extends javax.swing.JFrame {

    /**
     * Creates new form startemails
     */
    public startemails() {
        initComponents();
        cont.setVisible(false);
    }
    
    
    
    public static boolean report = false;
    public static boolean open = false;
    public static boolean delete = false;
    
    public class Email {
        private final String type;
        private final String sender;
        private final String subject;
        public static int numEmails;
        
        public Email(String type, String sender, String subject){
            this.type = type;
            this.sender = sender;
            this.subject = subject;
            numEmails ++;
        }
        
        public String getType(){
            return type;
        }
        
        public String getSender(){
            return sender;
        }
        
        public String getSubject(){
            return subject;
        }
        
        public static int getNumEmails(){
            return numEmails;
        }
        
        public static void setNumEmails(int num){
            numEmails = num;
        }
        
    }
    
    public class Unsafe extends Email {
        private final String level;
        private final String reason;
        
        public Unsafe(String type, String sender, String subject, String level, String reason){
            super(type, sender, subject);
            this.level = level;
            this.reason = reason;
        }
        
        public String getLevel(){
            return level;
        }
        
        public String getReason(){
            return reason;
        }
       
    }
    
    public class Safe extends Email {
        private final String something;
        private final String reason;
        
        
        public Safe(String type, String sender, String subject, String something, String reason){
            super(type, sender, subject);
            this.reason = reason;
            this.something = something;
        }
        
        public String getReason(){
            return reason;
        }
        
        public String getSomething(){
            return something;
        }
    }
    
    
    public Email[] readEmails(File file){
        String [][] emails = new String [6][5];
        int num = 0;
        try{
            Scanner read = new Scanner(file);
            while(read.hasNext()){
                String line = read.nextLine();
                String [] data = line.split(",");
                for(int i = 0;i < data.length; i++){
                    emails[num][i] = data[i].trim();
                }
            num++;
            } 
        }catch(IOException e){
            System.out.println("IO Exception!");
        }
        Email[] emailList = new Email [6];
        for (int i = 0; i < emails.length; i++){
            if (emails[i][2].equalsIgnoreCase("Safe")){
                emailList[i] = new Safe(emails[i][0], emails[i][1], emails[i][2], emails[i][3], emails[i][4]);
            }
            else if (emails[i][2].equalsIgnoreCase("Unsafe")){
                emailList[i] = new Unsafe(emails[i][0], emails[i][1], emails[i][2], emails[i][3], emails[i][4]);
            }else{
                emailList[i] = new Email(emails[i][0], emails[i][1], emails[i][2]);
            }
            
        }
        return emailList;
    }
    
    public void displayDetails(Email[] emails){
        int i = Email.numEmails;
        while (i > 0){
            title.setText(emails[i].getSubject());
            send.setText(emails[i].getSender());
            if (report){
                
            }
            else if (open){
                
            }
            else if (delete){
                
            }
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        whitebox = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        send = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rep = new javax.swing.JButton();
        op = new javax.swing.JButton();
        del = new javax.swing.JButton();
        cont = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        whitebox.setBackground(new java.awt.Color(255, 255, 255));
        whitebox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        title.setText("Email Title details go here");
        whitebox.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 30));
        whitebox.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 540, 20));

        send.setText("Sender");
        whitebox.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText("Please Choose An Option Below");
        whitebox.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 500, 260));
        whitebox.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 540, 10));

        rep.setText("Report");
        rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repActionPerformed(evt);
            }
        });
        whitebox.add(rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        op.setText("Open");
        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });
        whitebox.add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        whitebox.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        cont.setText("Continue");
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });
        whitebox.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 220, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gmail.png"))); // NOI18N
        whitebox.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.add(whitebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repActionPerformed
        report = true;
        rep.setVisible(false);
        del.setVisible(false);
        op.setVisible(false);
        cont.setVisible(true);
        
    }//GEN-LAST:event_repActionPerformed

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
        report = false;
        open = false;
        delete = false;
        
        rep.setVisible(true);
        del.setVisible(true);
        op.setVisible(true);
        cont.setVisible(false);
    }//GEN-LAST:event_contActionPerformed

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        open = true;
        rep.setVisible(false);
        del.setVisible(false);
        op.setVisible(false);
        cont.setVisible(true);
    }//GEN-LAST:event_opActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        delete = true;
        rep.setVisible(false);
        del.setVisible(false);
        op.setVisible(false);
        cont.setVisible(true);
    }//GEN-LAST:event_delActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startemails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startemails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startemails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startemails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startemails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton cont;
    private javax.swing.JButton del;
    private javax.swing.JLabel info;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton op;
    private javax.swing.JButton rep;
    private javax.swing.JLabel send;
    private javax.swing.JLabel title;
    private javax.swing.JPanel whitebox;
    // End of variables declaration//GEN-END:variables
}
