/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alina
 */
import java.awt.Color;
public class toEmail extends javax.swing.JFrame {

    /**
     * Creates new form toEmail
     */
    public toEmail() {
        initComponents();
        label.setText(
                "<html>" +
                "Thank you for creating an account with Data Defender.<br>" +
                "You may now move on to learning about how to identify suspicious emails.<br><br>" +
                "Your Current score is…." + intro.gameScore.getScore() +
                "</html>"
                ); 
        whitebox.setBackground(new Color(255, 255, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        graybox = new javax.swing.JPanel();
        move = new javax.swing.JButton();
        whitebox = new javax.swing.JPanel();
        steamtxt = new javax.swing.JLabel();
        steamicon = new javax.swing.JLabel();
        riottxt = new javax.swing.JLabel();
        rioticon = new javax.swing.JLabel();
        chrometxt = new javax.swing.JLabel();
        chromeicon = new javax.swing.JLabel();
        netbeanstxt = new javax.swing.JLabel();
        recyclingtxt = new javax.swing.JLabel();
        netbeansicon = new javax.swing.JLabel();
        recyclingbin = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        windowsbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label.setText("<html> Welcome to Data Defender! <br> <br> To begin this game, please create an account. <br> <br>  Click OK to begin. </html>");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, -1));

        exit.setForeground(new java.awt.Color(153, 153, 153));
        exit.setText("X");
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 10, -1));

        banner.setForeground(new java.awt.Color(153, 153, 153));
        banner.setText("Setup Software");
        getContentPane().add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        graybox.setBackground(new java.awt.Color(220, 220, 220));
        graybox.setPreferredSize(new java.awt.Dimension(400, 60));

        move.setText("OK");
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grayboxLayout = new javax.swing.GroupLayout(graybox);
        graybox.setLayout(grayboxLayout);
        grayboxLayout.setHorizontalGroup(
            grayboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grayboxLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        grayboxLayout.setVerticalGroup(
            grayboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grayboxLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(move)
                .addContainerGap())
        );

        getContentPane().add(graybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 300, 50));

        whitebox.setBackground(new java.awt.Color(255, 255, 255));
        whitebox.setPreferredSize(new java.awt.Dimension(400, 250));

        javax.swing.GroupLayout whiteboxLayout = new javax.swing.GroupLayout(whitebox);
        whitebox.setLayout(whiteboxLayout);
        whiteboxLayout.setHorizontalGroup(
            whiteboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        whiteboxLayout.setVerticalGroup(
            whiteboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(whitebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, 240));

        steamtxt.setForeground(new java.awt.Color(255, 255, 255));
        steamtxt.setText("Steam");
        getContentPane().add(steamtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        steamicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steamicon.png"))); // NOI18N
        getContentPane().add(steamicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        riottxt.setForeground(new java.awt.Color(255, 255, 255));
        riottxt.setText("Riot Client");
        getContentPane().add(riottxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        rioticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rioticon.png"))); // NOI18N
        getContentPane().add(rioticon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, 50));

        chrometxt.setForeground(new java.awt.Color(255, 255, 255));
        chrometxt.setText("Google Chrome");
        getContentPane().add(chrometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        chromeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chromeicon.png"))); // NOI18N
        getContentPane().add(chromeicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        netbeanstxt.setForeground(new java.awt.Color(255, 255, 255));
        netbeanstxt.setText("Netbeans");
        getContentPane().add(netbeanstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        recyclingtxt.setForeground(new java.awt.Color(255, 255, 255));
        recyclingtxt.setText("Recycling Bin");
        getContentPane().add(recyclingtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        netbeansicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/netbeansicon.png"))); // NOI18N
        getContentPane().add(netbeansicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        recyclingbin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/recyclingicon.png"))); // NOI18N
        getContentPane().add(recyclingbin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        title.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Data Defender");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 170, 60));

        windowsbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(windowsbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 723, 429));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        new startemails().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_moveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel chromeicon;
    private javax.swing.JLabel chrometxt;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel graybox;
    private javax.swing.JLabel label;
    private javax.swing.JButton move;
    private javax.swing.JLabel netbeansicon;
    private javax.swing.JLabel netbeanstxt;
    private javax.swing.JLabel recyclingbin;
    private javax.swing.JLabel recyclingtxt;
    private javax.swing.JLabel rioticon;
    private javax.swing.JLabel riottxt;
    private javax.swing.JLabel steamicon;
    private javax.swing.JLabel steamtxt;
    private javax.swing.JLabel title;
    private javax.swing.JPanel whitebox;
    private javax.swing.JLabel windowsbackground;
    // End of variables declaration//GEN-END:variables
}
