/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alina
 */
public class toEmail extends javax.swing.JFrame {

    /**
     * Creates new form toEmail
     */
    public toEmail() {
        initComponents();
        label.setText(
            "Thank you for creating an account with Data Defender.\n" +
            "You may now move on to learning about how to identify \n" +
            "suspicious emails.\n\n" +
            "Your Current score is… " + intro.gameScore.getScore()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        move = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        graybox = new javax.swing.JPanel();
        whitebox = new javax.swing.JPanel();
        steamtxt = new javax.swing.JLabel();
        steamicon = new javax.swing.JLabel();
        riottxt = new javax.swing.JLabel();
        rioticon = new javax.swing.JLabel();
        chrometxt = new javax.swing.JLabel();
        chromeicon = new javax.swing.JLabel();
        netbeanstxt = new javax.swing.JLabel();
        recyclingtxt = new javax.swing.JLabel();
        netbeansicon = new javax.swing.JLabel();
        recyclingbin = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        windowsbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label.setText("<html>\nWelcome to Data Defender!\n<br>\n<br>\nTo begin this game, please create an account.\n<br>\n<br> \nClick OK to begin.\n</html>");

        move.setText("OK");
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });

        exit.setForeground(new java.awt.Color(153, 153, 153));
        exit.setText("X");

        banner.setForeground(new java.awt.Color(153, 153, 153));
        banner.setText("Setup Software");

        graybox.setBackground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout grayboxLayout = new javax.swing.GroupLayout(graybox);
        graybox.setLayout(grayboxLayout);
        grayboxLayout.setHorizontalGroup(
            grayboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        grayboxLayout.setVerticalGroup(
            grayboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        whitebox.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout whiteboxLayout = new javax.swing.GroupLayout(whitebox);
        whitebox.setLayout(whiteboxLayout);
        whiteboxLayout.setHorizontalGroup(
            whiteboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        whiteboxLayout.setVerticalGroup(
            whiteboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        steamtxt.setForeground(new java.awt.Color(255, 255, 255));
        steamtxt.setText("Steam");

        steamicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/steamicon.png"))); // NOI18N

        riottxt.setForeground(new java.awt.Color(255, 255, 255));
        riottxt.setText("Riot Client");

        rioticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rioticon.png"))); // NOI18N

        chrometxt.setForeground(new java.awt.Color(255, 255, 255));
        chrometxt.setText("Google Chrome");

        chromeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chromeicon.png"))); // NOI18N

        netbeanstxt.setForeground(new java.awt.Color(255, 255, 255));
        netbeanstxt.setText("Netbeans");

        recyclingtxt.setForeground(new java.awt.Color(255, 255, 255));
        recyclingtxt.setText("Recycling Bin");

        netbeansicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/netbeansicon.png"))); // NOI18N

        recyclingbin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/recyclingicon.png"))); // NOI18N

        title.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Data Defender");

        windowsbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(steamicon))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(recyclingbin))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(banner))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(steamtxt))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(402, 402, 402)
                            .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(riottxt))
                        .addComponent(windowsbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(rioticon))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(netbeanstxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(netbeansicon))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(chromeicon))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(recyclingtxt))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(chrometxt)))
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(whitebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(graybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(steamicon))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(rioticon))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(netbeanstxt))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(whitebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(netbeansicon))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(recyclingbin))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(chromeicon))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(banner))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(380, 380, 380)
                            .addComponent(steamtxt))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(recyclingtxt))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(chrometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(250, 250, 250)
                            .addComponent(move))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addComponent(riottxt))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(graybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(windowsbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        new startemails().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_moveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel chromeicon;
    private javax.swing.JLabel chrometxt;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel graybox;
    private javax.swing.JLabel label;
    private javax.swing.JButton move;
    private javax.swing.JLabel netbeansicon;
    private javax.swing.JLabel netbeanstxt;
    private javax.swing.JLabel recyclingbin;
    private javax.swing.JLabel recyclingtxt;
    private javax.swing.JLabel rioticon;
    private javax.swing.JLabel riottxt;
    private javax.swing.JLabel steamicon;
    private javax.swing.JLabel steamtxt;
    private javax.swing.JLabel title;
    private javax.swing.JPanel whitebox;
    private javax.swing.JLabel windowsbackground;
    // End of variables declaration//GEN-END:variables
}
