/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alina
 */
public class ToSquiz extends javax.swing.JFrame {

    // array for questions (10 questions
    private String[] questionsArray = { 
        "Q1: Did the Terms mention collecting location data?",
        "Q2: Which sea creature was mentioned in the ToS?",
        "Q3: Does Data Defender sell your personal information?",
        "Q4: What may be tracked for learning analytics?",
        "Q5: What should you avoid doing while using the service?",
        "Q6: Which of the following is mentioned about cookies?",
        "Q7: What does Data Defender store to improve user experience?",
        "Q8: Does Data Defender use your email for marketing purposes?",
        "Q9: What is a risk of sleepwalking while using this app?",
        "Q10: How are backups stored in Data Defender?"
    };
    
    // 2D array for answer options (4 options for a,b,c and d)
    private String[][] answerOptions = {
        {"Yes", "No", "Maybe", "Not sure"},
        {"SpongeBob", "Gary", "Both", "None"},
        {"Yes", "No", "Maybe", "Not sure"},
        {"Button presses", "Food choices", "Duck thoughts", "Emails"},
        {"Sleepwalking", "Eating", "Wrestling", "None"},
        {"For analytics", "For ads", "For login", "For security"},
        {"Username & password", "Phone number", "Financial data", "Location"},
        {"Yes", "No", "For account recovery", "For alerts"},
        {"Injury", "Data loss", "System crash", "None"},
        {"Guarded by squirrel", "Cloud storage", "Local disks", "Encrypted"}
    };
    
    // correct answers array (indexing starts from 0)
    private int[] correctAnswersIndex = {0, 1, 1, 0, 0, 0, 3, 0, 2, 1};
    // tracks which question the program is on
    private int currentQuestionIndex = 0; 
    // keeps track of current score
    private int totalScore = 0;
    // constant variable for points received from correct answer
    private static final int POINTS_PER_CORRECT_ANSWER = 1;
    
    /**
     * Creates new form ToSquiz
     */
    public ToSquiz() {
        initComponents();
        // load in questions
        loadQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        quetions = new javax.swing.JLabel();
        optionC = new javax.swing.JLabel();
        optionA = new javax.swing.JLabel();
        optionD = new javax.swing.JLabel();
        optionB = new javax.swing.JLabel();
        answerA = new javax.swing.JButton();
        answerB = new javax.swing.JButton();
        answerC = new javax.swing.JButton();
        answerD = new javax.swing.JButton();
        score = new javax.swing.JLabel();
        answerChecker = new javax.swing.JLabel();
        contrinue = new javax.swing.JButton();
        leave = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Lets see if you actually read the terms of service");

        quetions.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        quetions.setText("Q1:");
        quetions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        optionC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        optionC.setText("C:");
        optionC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        optionA.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        optionA.setText("A:");
        optionA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        optionD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        optionD.setText("D:");
        optionD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        optionB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        optionB.setText("B:");
        optionB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        answerA.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        answerA.setText("Option A");
        answerA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        answerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerAActionPerformed(evt);
            }
        });

        answerB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        answerB.setText("Option B");
        answerB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        answerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBActionPerformed(evt);
            }
        });

        answerC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        answerC.setText("Option C");
        answerC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        answerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCActionPerformed(evt);
            }
        });

        answerD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        answerD.setText("Option D");
        answerD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        answerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerDActionPerformed(evt);
            }
        });

        score.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        score.setText("Score: ");
        score.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        answerChecker.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        answerChecker.setText("Answer Checker");

        contrinue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        contrinue.setText("Continue");
        contrinue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contrinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrinueActionPerformed(evt);
            }
        });

        leave.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        leave.setText("Back");
        leave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(answerC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answerD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(optionC, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(quetions, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(optionB, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(optionD, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(answerChecker, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(234, 234, 234))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(answerB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(answerA, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(372, 372, 372)))))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contrinue, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(score)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(quetions)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionA)
                    .addComponent(optionC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionB)
                    .addComponent(optionD))
                .addGap(18, 18, 18)
                .addComponent(answerChecker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrinue)
                    .addComponent(leave))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBActionPerformed
        // TODO add your handling code here:
        checkAnswer(1);
    }//GEN-LAST:event_answerBActionPerformed

    private void answerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCActionPerformed
        // TODO add your handling code here:
        checkAnswer(2);
    }//GEN-LAST:event_answerCActionPerformed

    private void answerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerDActionPerformed
        // TODO add your handling code here:
        checkAnswer(3);
    }//GEN-LAST:event_answerDActionPerformed

    private void answerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerAActionPerformed
        // TODO add your handling code here:
        checkAnswer(0);
    }//GEN-LAST:event_answerAActionPerformed

    private void contrinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrinueActionPerformed
        // TODO add your handling code here:
        // move to email checking game
        new startemails().setVisible(true);
        this.setVisible(false);
        //add values to the score
        intro.score += totalScore;
    }//GEN-LAST:event_contrinueActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        // TODO add your handling code here:
        // move to homepage
        new homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_leaveActionPerformed
    private void disableOptionButtons() {
        answerA.setEnabled(false);
        answerB.setEnabled(false);
        answerC.setEnabled(false);
        answerD.setEnabled(false);
    }
    
    private void loadQuestion() {
        // checks that all questions have been gone through and disclose final score
        if (currentQuestionIndex >= questionsArray.length) {
            quetions.setText("Quiz finished!");
            optionA.setText("");
            optionB.setText("");
            optionC.setText("");
            optionD.setText("");
            
            // show final score
            answerChecker.setText("Final score: " + totalScore + "/" + questionsArray.length);
            
            // disable option buttons 
            disableOptionButtons();
            return;
        }
        
        // sets question to correct question based on index
        quetions.setText(questionsArray[currentQuestionIndex]);

        // set answer options based on index
        optionA.setText("A: " + answerOptions[currentQuestionIndex][0]);
        optionB.setText("B: " + answerOptions[currentQuestionIndex][1]);
        optionC.setText("C: " + answerOptions[currentQuestionIndex][2]);
        optionD.setText("D: " + answerOptions[currentQuestionIndex][3]);
    }
    
private void checkAnswer(int selectedIndex) {
    // checks if answer is correct
    if (selectedIndex == correctAnswersIndex[currentQuestionIndex]) {
        // inscrease total score
        totalScore += POINTS_PER_CORRECT_ANSWER;
        // set text to correct asnwer
        answerChecker.setText("Correct!");
        // set text colour green
        answerChecker.setForeground(new java.awt.Color(0, 153, 0));
    } else {
        // set text to incorrect
        answerChecker.setText("Incorrect!");
        // set colour to red
        answerChecker.setForeground(java.awt.Color.RED);
    }

    // update score tracker
    score.setText("Score: " + totalScore);
    currentQuestionIndex++;
    loadQuestion();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToSquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToSquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToSquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToSquiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToSquiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerA;
    private javax.swing.JButton answerB;
    private javax.swing.JButton answerC;
    private javax.swing.JLabel answerChecker;
    private javax.swing.JButton answerD;
    private javax.swing.JButton contrinue;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton leave;
    private javax.swing.JLabel optionA;
    private javax.swing.JLabel optionB;
    private javax.swing.JLabel optionC;
    private javax.swing.JLabel optionD;
    private javax.swing.JLabel quetions;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
